#!/usr/bin/perl

use strict;
use warnings;

sub print_err {
	my ($str) = @_;

	print STDERR "Error: $str\n";

	exit (1);
}

sub get_current_volumes {
	my ($left, $right) = @_;
	open P, "mixerctl outputs.master|";

	my $line = <P>;
	close P;

	if ($line =~ m/(\d+),(\d+)/) {
		$$left = $1;
		$$right = $2;

		return 1;
	}
		
	return 0;
}

sub set_new_volumes {
	my ($new_left, $new_right) = @_;

	my $cmd = "mixerctl outputs.master=$new_left,$new_right";

	my $ret = system($cmd);

	return $ret;
}

sub main {
	my (@args) = @_;
	my $argc = scalar(@args);	

	my ($inc, $dec) = (0, 0);

	for (my $i = 0; $i < $argc; $i++) {
		if ($args[$i] =~ /\+(\d+)/) {
			$inc = $1;
		}

		if ($args[$i] =~ /\-(\d+)/) {
			$dec = $1
		}
	}

	my ($left, $right) = (0, 0);

	if (!get_current_volumes(\$left, \$right)) {
		print_err("couldn't get current volumes");
	}

	$left -= $dec; $right -= $dec;
	$left += $inc; $right += $inc; 

	return set_new_volumes($left, $right);	
}

main(@ARGV);

